/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar/AppSidebar.vue')['default']
    ClearableInput: typeof import('./components/UI/ClearableInput/ClearableInput.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconMdiAlertCircle: typeof import('~icons/mdi/alert-circle')['default']
    IconMdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    IconMdiAxisXArrow: typeof import('~icons/mdi/axis-x-arrow')['default']
    IconMdiAxisZArrow: typeof import('~icons/mdi/axis-z-arrow')['default']
    IconMdiCameraFlip: typeof import('~icons/mdi/camera-flip')['default']
    IconMdiChartScatterPlot: typeof import('~icons/mdi/chart-scatter-plot')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCloseCircleOutline: typeof import('~icons/mdi/close-circle-outline')['default']
    IconMdiCloudOutline: typeof import('~icons/mdi/cloud-outline')['default']
    IconMdiCloudUpload: typeof import('~icons/mdi/cloud-upload')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiCubeOutline: typeof import('~icons/mdi/cube-outline')['default']
    IconMdiFileCloud: typeof import('~icons/mdi/file-cloud')['default']
    IconMdiFileQuestion: typeof import('~icons/mdi/file-question')['default']
    IconMdiFolder: typeof import('~icons/mdi/folder')['default']
    IconMdiFolderAlert: typeof import('~icons/mdi/folder-alert')['default']
    IconMdiFolderOpen: typeof import('~icons/mdi/folder-open')['default']
    IconMdiLoading: typeof import('~icons/mdi/loading')['default']
    IconMdiMagnifyMinus: typeof import('~icons/mdi/magnify-minus')['default']
    IconMdiMagnifyPlus: typeof import('~icons/mdi/magnify-plus')['default']
    IconMdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    IconMdiMenuOpen: typeof import('~icons/mdi/menu-open')['default']
    IconMdiTrayArrowDown: typeof import('~icons/mdi/tray-arrow-down')['default']
    IconMdiUpload: typeof import('~icons/mdi/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
